version: "3.8"
services:
  db:
    image: postgres:14
    container_name: esports-db
    environment:
      POSTGRES_DB: esports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    container_name: esports-api
    build: ./src
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/esports
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data:
